name: 📄 generate_report

on:
  schedule:
    - cron: '15 5 * * *'  # JST 14:15（日本時間 5:15am）
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_report.py
        run: |
          python generate_report.py
